OFFICIAL_TEAMS = [
    "Argentina",
    "Brazil",
    "France",
    "Spain",
    "England",
    "Portugal",
    "Germany",
    "Netherlands",
    "Belgium",
    "Italy",
    "Croatia",
    "Uruguay",
    "Mexico",
    "United States",
    "Canada",
    "Japan",
    "South Korea",
    "Australia",
    "Morocco",
    "Senegal",
    "Nigeria",
    "Cameroon",
    "Tunisia",
    "Egypt",
    "Switzerland",
    "Denmark",
    "Sweden",
    "Poland",
    "Austria",
    "Czech Republic",
    "Serbia",
    "Turkey",
    "Iran",
    "Saudi Arabia",
    "Qatar",
    "Costa Rica",
    "Panama",
    "Ecuador",
    "Colombia",
    "Chile",
    "Paraguay",
    "Peru",
    "Algeria",
    "Ivory Coast",
    "Ghana",
    "Mali",
    "Norway",
    "Ukraine"
]